backend:
  name: proxy
  proxy_url: https://eaeaawards.netlify.app/api/v1
  auth_endpoint: https://eaeaawards.netlify.app/.netlify/identity

media_folder: "static/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

site_url: https://eaeaawards.netlify.app
admin_url: https://eaeaawards.netlify.app/admin/
